import type { ClassAnalyticsOverviewData } from "./types";

export const CLASS_ANALYTICS_OVERVIEW_MOCK: ClassAnalyticsOverviewData = {
  title: "Class Analytics: CS-402 Advanced Algorithms",
  subtitle: "Cohort Performance Summary • Semester 1, 2024",
  resourceUsage: [
    { key: "videos", label: "Videos", percent: 75 },
    { key: "pdfs", label: "PDFs", percent: 15 },
    { key: "quizzes", label: "Quizzes", percent: 10 },
  ],
  kpis: [
    {
      id: "avg-grade",
      label: "Avg Grade",
      value: "84%",
      deltaLabel: "+2.4%",
      deltaTone: "up",
      tone: "primary",
    },
    {
      id: "attendance-rate",
      label: "Attendance Rate",
      value: "94%",
      deltaLabel: "+0.8%",
      deltaTone: "up",
      tone: "secondary",
    },
    {
      id: "completion-rate",
      label: "Completion Rate",
      value: "88%",
      deltaLabel: "-1.2%",
      deltaTone: "down",
      tone: "warning",
    },
    {
      id: "engagement-score",
      label: "Engagement Score",
      value: "92%",
      deltaLabel: "+5.1%",
      deltaTone: "up",
      tone: "purple",
    },
  ],
  aiInsights: [
    {
      id: "insight-1",
      icon: "warning",
      text: "Engagement dropped mid-week. Consider a knowledge check for Module 4.",
    },
    {
      id: "insight-2",
      icon: "trend",
      text: "Completion rates are 12% higher than the previous cohort at this stage.",
    },
    {
      id: "insight-3",
      icon: "search",
      text: "3 students haven't accessed the 'Complexity Analysis' PDF in 5 days.",
    },
  ],
  heatmap: [
    "low",
    "mid",
    "high",
    "veryHigh",
    "mid",
    "low",
    "empty",
    "mid",
    "mid",
    "veryHigh",
    "high",
    "mid",
    "low",
    "empty",
    "mid",
    "high",
    "high",
    "mid",
    "mid",
    "mid",
    "empty",
  ],
  popularContent: [
    {
      id: "popular-1",
      kind: "video",
      title: "Big O Notation Recap",
      meta: "42 views today",
    },
    {
      id: "popular-2",
      kind: "doc",
      title: "Sorting Algorithms Cheat Sheet",
      meta: "28 views today",
    },
  ],
  students: [
    {
      id: "student-ek",
      initials: "EK",
      name: "Elena Kostic",
      attendanceLabel: "98%",
      avgScoreLabel: "94%",
      completedLabel: "12/12",
      statusLabel: "Excellent",
      statusTone: "excellent",
    },
    {
      id: "student-mm",
      initials: "MM",
      name: "Marcus Miller",
      attendanceLabel: "82%",
      avgScoreLabel: "71%",
      completedLabel: "9/12",
      statusLabel: "At Risk",
      statusTone: "atRisk",
    },
    {
      id: "student-st",
      initials: "ST",
      name: "Sarah Tan",
      attendanceLabel: "94%",
      avgScoreLabel: "85%",
      completedLabel: "11/12",
      statusLabel: "Stable",
      statusTone: "stable",
    },
  ],
};
